param(
    [Parameter(Mandatory = $true)]
    [string] $SourceDir,

    [string] $ModDir = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path,
    [string] $TargetImageDir = "graphics/ui/slices",
    [string] $TargetLuaFile = "lib/ui_slices.lua"
)

$ErrorActionPreference = "Stop"

function ConvertTo-SliceKey {
    param([string] $Name)
    return ($Name -replace '[^A-Za-z0-9]+', '_').Trim('_').ToLowerInvariant()
}

function Escape-LuaString {
    param([string] $Value)
    return ($Value -replace '\\', '\\' -replace '"', '\"')
}

function Get-PngSize {
    param([string] $Path)

    $bytes = [System.IO.File]::ReadAllBytes($Path)
    if ($bytes.Length -lt 24) {
        throw "PNG is too small to contain a header: $Path"
    }

    $pngSignature = @(137, 80, 78, 71, 13, 10, 26, 10)
    for ($i = 0; $i -lt $pngSignature.Count; $i++) {
        if ($bytes[$i] -ne $pngSignature[$i]) {
            throw "File is not a PNG: $Path"
        }
    }

    $width = ([int] $bytes[16] * 16777216) + ([int] $bytes[17] * 65536) + ([int] $bytes[18] * 256) + [int] $bytes[19]
    $height = ([int] $bytes[20] * 16777216) + ([int] $bytes[21] * 65536) + ([int] $bytes[22] * 256) + [int] $bytes[23]
    return @{ Width = $width; Height = $height }
}

$sourcePath = Resolve-Path $SourceDir
$jsonPath = Join-Path $sourcePath "slices.json"
if (-not (Test-Path $jsonPath)) {
    throw "Missing slices.json in $sourcePath"
}

$manifest = Get-Content -Raw $jsonPath | ConvertFrom-Json
if (-not $manifest.slices -or $manifest.slices.Count -eq 0) {
    throw "slices.json does not contain any slices"
}

$targetImagePath = Join-Path $ModDir $TargetImageDir
$targetLuaPath = Join-Path $ModDir $TargetLuaFile
New-Item -ItemType Directory -Force $targetImagePath | Out-Null
New-Item -ItemType Directory -Force (Split-Path $targetLuaPath -Parent) | Out-Null

$seenNames = @{}
$seenKeys = @{}
$entries = @()

foreach ($slice in $manifest.slices) {
    foreach ($field in @("name", "x", "y", "w", "h")) {
        if ($null -eq $slice.$field) {
            throw "Slice is missing '$field': $($slice | ConvertTo-Json -Compress)"
        }
    }

    $name = [string] $slice.name
    $key = ConvertTo-SliceKey $name
    if ([string]::IsNullOrWhiteSpace($key)) {
        throw "Slice name does not produce a usable key: '$name'"
    }
    if ($seenNames.ContainsKey($name)) {
        throw "Duplicate slice name in slices.json: $name"
    }
    if ($seenKeys.ContainsKey($key)) {
        throw "Duplicate generated slice key '$key' from '$name' and '$($seenKeys[$key])'"
    }
    $seenNames[$name] = $true
    $seenKeys[$key] = $name

    $sourceImage = Join-Path $sourcePath ($name + ".png")
    if (-not (Test-Path $sourceImage)) {
        throw "Missing PNG for slice '$name': $sourceImage"
    }

    $size = Get-PngSize $sourceImage
    $targetFileName = $name + ".png"
    $targetImage = Join-Path $targetImagePath $targetFileName
    Copy-Item -LiteralPath $sourceImage -Destination $targetImage -Force

    $entries += [ordered] @{
        name = $name
        key = $key
        file = "__LilEinstein__/" + ($TargetImageDir -replace '\\', '/') + "/" + $targetFileName
        x = [int] $slice.x
        y = [int] $slice.y
        w = [int] $slice.w
        h = [int] $slice.h
        image_w = [int] $size.Width
        image_h = [int] $size.Height
    }
}

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("-- Generated by scripts/import_ui_slices.ps1. Do not edit by hand.")
$lines.Add("local slices = {")
foreach ($entry in $entries) {
    $lines.Add("    {")
    $lines.Add('        name = "' + (Escape-LuaString $entry.name) + '",')
    $lines.Add('        key = "' + (Escape-LuaString $entry.key) + '",')
    $lines.Add('        file = "' + (Escape-LuaString $entry.file) + '",')
    $lines.Add("        x = $($entry.x),")
    $lines.Add("        y = $($entry.y),")
    $lines.Add("        w = $($entry.w),")
    $lines.Add("        h = $($entry.h),")
    $lines.Add("        image_w = $($entry.image_w),")
    $lines.Add("        image_h = $($entry.image_h)")
    $lines.Add("    },")
}
$lines.Add("}")
$lines.Add("")
$lines.Add("local by_name = {}")
$lines.Add("local by_key = {}")
$lines.Add("for _, item in ipairs(slices) do")
$lines.Add("    by_name[item.name] = item")
$lines.Add("    by_key[item.key] = item")
$lines.Add("end")
$lines.Add("")
$lines.Add("return {")
$lines.Add("    slices = slices,")
$lines.Add("    by_name = by_name,")
$lines.Add("    by_key = by_key")
$lines.Add("}")

Set-Content -LiteralPath $targetLuaPath -Value ($lines -join [Environment]::NewLine) -Encoding ASCII

Write-Host "Imported $($entries.Count) slices"
Write-Host "Images: $targetImagePath"
Write-Host "Registry: $targetLuaPath"
